apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  # deployment labels
  labels:
    purpose: blue-green
    project: roboshop
    color: blue
spec:
  replicas: 3
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: blue-green
      project: roboshop
      color: blue
  # This is pod definition
  template:
    metadata:
      labels:
        purpose: blue-green
        project: roboshop
        color: blue
    spec:
      containers:
      - name: nginx
        image: nginx:latest